### PR TITLE
fix: return cores from replicant

### LINKED ISSUE #75: `mria_mnesia:cluster_nodes(cores)` giving inconsistent result on replicant node
```elixir
iex(emqx@emqx-15.int.thalesmg)3> :ekka_cluster.info()
%{
  running_nodes: [:"emqx@emqx-0.int.thalesmg", :"emqx@emqx-1.int.thalesmg",
   :"emqx@emqx-10.int.thalesmg", :"emqx@emqx-11.int.thalesmg",
   :"emqx@emqx-12.int.thalesmg", :"emqx@emqx-13.int.thalesmg",
   :"emqx@emqx-14.int.thalesmg", :"emqx@emqx-15.int.thalesmg",
   :"emqx@emqx-16.int.thalesmg", :"emqx@emqx-17.int.thalesmg",
   :"emqx@emqx-18.int.thalesmg", :"emqx@emqx-19.int.thalesmg",
   :"emqx@emqx-2.int.thalesmg", :"emqx@emqx-20.int.thalesmg",
   :"emqx@emqx-3.int.thalesmg", :"emqx@emqx-4.int.thalesmg",
   :"emqx@emqx-5.int.thalesmg", :"emqx@emqx-6.int.thalesmg",
   :"emqx@emqx-7.int.thalesmg", :"emqx@emqx-8.int.thalesmg",
   :"emqx@emqx-9.int.thalesmg"],
  stopped_nodes: []
}
iex(emqx@emqx-15.int.thalesmg)4> :mria_mnesia.cluster_nodes(:cores)
[:"emqx@emqx-15.int.thalesmg"]
iex(emqx@emqx-15.int.thalesmg)5> :mria_rlog.role()   
:replicant
```

### PR DESCRIPTION
**Pull request by thalesmg**
Fixes #75 .

Calling `mnesia:system_info(db_nodes)` on a replicant will return only
the replicant self node.  We need to check with the upstream core the
true list of all core nodes.

### CODE REVIEW

**Comment by thalesmg** [comment]
The addition of the `cores` clause in `mria_mnesia:cluster_nodes/1` is quite [recent](https://github.com/emqx/mria/commit/a0652a054003c7bead8d3a0aefa43a086653bed4), so I just added a check to consult a core node if it's called from a replicant, since calling it in a replicant yields only the replicant node.

I'm afraid I didn't quite understand what could be the issue here.  `mria_mnesia:cluster_nodes(cores)` is expected to return `[node()]` in a replicant?

By the way, I noticed this changed recently as well:

```diff
is_node_in_cluster() ->
-    mria_mnesia:cluster_nodes(all) =/= [node()].
+    cluster_nodes(cores) =/= [node()].
```

With the current behavior (returning `node()` in a replicant), this works.  Maybe we should keep using `all`?

**Comment by k32** [comment]
> By the way, I noticed this changed recently as well:

This was a fix to an issue where autocluster didn't trigger because the core node thought it's already in the cluster due to the replicants.

File: src/mria_mnesia.erl [hunk 1]
```diff
@@ -208,7 +208,22 @@ cluster_nodes(running) ->
...
 cluster_nodes(cores) ->
-    db_nodes().
+    case mria_rlog:role() of
+        core ->
+            db_nodes();
+        replicant ->
+            case mria_status:shards_up() of
+                [Shard | _] ->
+                    {ok, CoreNode} = mria_status:upstream_node(Shard),
+                    case mria_lib:rpc_call(CoreNode, ?MODULE, ?FUNCTION_NAME, [cores]) of
```
Comment (k32) [inline src/mria_mnesia.erl:218]: Maybe this data can be extracted from `mria_lb` to avoid RPC?

Comment (thalesmg) [reply src/mria_mnesia.erl:218]: You are absolutely right.  :see_no_evil:

**Review by k32 — APPROVED** [review]

**Review by ieQu1 — APPROVED** [review]
